README.md
Creating community README with basic governance outline and project overview
=> Creating community README

README.md
Add a TOC and links to installation documents for Clear Containers and runV.
=> Add getting started info

CODE_OF_CONDUCT.md
Added that standard code of conduct document.
Fixes #7.
=> docs: Added CoC doc.

CONTRIBUTING.md
This doc will be referenced by all the other Kata Containers
repositories.
Fixes #5.
=> docs: Add central contributing doc

LICENSE
Add the standard license file.
Fixes #21.
=> docs: Add LICENSE file

statusreports/REPORT_TEMPLATE.md
Creates a new folder for weekly project status report drafts to be placed for community collaboration and gives an example status report template.
Signed-off-by: Anne Bertucio anne@openstack.org
=> Creates a folder for weekly status drafts

CONTRIBUTING.md, PR-Review-Guide.md
Add a document with tips on how to review a PR.
Fixes #24.
=> docs: Add PR review guide

README.md
Fixes: #36
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
=> docs: Update "Users" part of README.md

CONTRIBUTING.md, Documentation-Review-Process.md
Create a new document that outlines the document review process.
Fixes #40.
=> docs: Add Doc review process doc

elections/README.md
Creates a new folder for all elections
information and adds a general README
for election process.
Signed-off-by: Anne Bertucio <anne@openstack.org>
=> Adds elections folder and README.md

elections/arch-committee-2018-09/WeiZhang.txt
Adding a text file to announce my candidacy.
Signed-off-by: Wei Zhang <zhangwei555@huawei.com>
=> Docs: announce candidacy

elections/arch-committee-2018-09/KalyXin.txt
Adds the text file for Kata-Container Arch Committee Candidacy
for Arm, which is required by the election process
Signed-off-by: Kaly Xin <Kaly.Xin@arm.com>
=> Docs: Kata-Containers Arch Committee Candidacy Declaration

elections/arch-committee-2018-09/EricErnst.txt
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
=> election: add candidacy for Eric Ernst

CONTRIBUTING.md
Info about how the CI works when a PR is opened.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> docs: add CI info to CONTRIBUTING.md

elections/arch-committee-2019-03/README.md
2 seats for elections, process starts in 2 weeks.
Fixes: #74
=> elections: Kick the March 2019 election off

elections/tools/README.md, elections/tools/generate_electorate.py
Signed-off-by: Tony Breeds <tony@bakeyournoodle.com>
=> Add first set of tools to generate the electorate

elections/arch-committee-2019-03/SamuelOrtiz.txt
I'd like to renew my seat at the AC committee.
Fixes: #79
=> elections: Add Samuel Ortiz candidacy

elections/arch-committee-2019-03/XuWang.txt
Let's work together for a better year.
Fixes: #81
Signed-off-by: Xu Wang <xu@hyper.sh>
=> elections: Add Xu Wang candidacy

elections/arch-committee-2019-03/Results.md
Add a results file to record the outcome of the March 2019 AC
elections.
Fixes: #83
=> elections: March 2019 AC results

CONTRIBUTING.md, VMT/VMT.md
Fix various issues with the markdown files in this repo.
Fixes #91.
=> Fix markdown

README.md
Fixes:#95
Change to Ant Financial
Signed-off-by: Xu Wang <xu@hyper.sh>
=> README: change the company of Xu Wang

CONTRIBUTING.md
Make re-vendoring steps clearer.
Fixes: #97
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
=> CONTRIBUTING: Make re-vendoring steps clearer

Backport-Guide.md, CONTRIBUTING.md, README.md, VMT/KCSA/KCSA-CVE-2019-5736.md
Correct spelling mistakes and formatting issues.
Fixes: #107.
=> docs: Fix typos and formatting

.ci/lib.sh, .ci/run.sh, .ci/setup.sh, .ci/static-checks.sh, .travis.yml, Rota-Process.md, VMT/VMT.md, elections/README.md, elections/arch-committee-2018-09/README.md, elections/arch-committee-2019-03/README.md, elections/arch-committee-2019-03/Results.md, elections/tools/README.md
Add a basic set of CI scripts to ensure doc PRs are checked.
Fixes: #112.
=> CI: Add CI scripts

Backport-Guide.md
Add more detail to the backport guide including some ASCII graphics to demonstrate backporting and formatting improvements.
Fixes: #110.
=> docs: backport guide improvements

elections/README.md, elections/arch-committee-2019-09/README.md
Signed-off-by: Ricardo Aravena <raravena80@gmail.com>
=> Adding September 2019 elections

elections/arch-committee-2019-09/EricErnst.txt
Fixes: #116
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
=> elections: Eric Ernst candidacy

elections/arch-committee-2019-09/HaominTsai.txt
Fixes: #118
Signed-off-by: haomin <caihaomin@huawei.com>
=> elections: HaominTsai candidacy

README.md, elections/README.md, elections/arch-committee-2019-09/Results.md
Fixes #122
Signed-off-by: Ricardo Aravena <raravena80@gmail.com>
=> docs: Adding September 2019 election results

elections/README.md, elections/arch-committee-2020-02/README.md, elections/arch-committee-2020-02/Results.md
Add the details and documentation for the Feb/March 2020 elections.
Fixes: #134
=> elections: 2020-02

elections/arch-committee-2020-02/DaveGilbert.txt
Signed-off-by: Dr. David Alan Gilbert <dgilbert@redhat.com>
=> elections: Dave Gilbert candidacy

elections/tools/README.md
The README was not overly clear on how/where you needed to update it
to cover the current election period, nor where it actually placed
the final results. Update to help future election helpers.
Fixes: #141
=> election: tools: update README

elections/arch-committee-2020-02/Results.md
Update with the results of the election.
Fixes: #143
=> elections: Feb. 2020: Record election results

README.md
I moved. Update my employer...
Signed-off-by: Eric Ernst <eric@amperecomputing.com>
=> architecture committee: update Eric's employer

README.md
Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>
=> Adds link to https://katacontainers.io/community/ in Community section.

elections/README.md, elections/arch-committee-2020-09/README.md, elections/arch-committee-2020-09/Results.md
Add the details and documentation for the September 2020 elections.
Fixes: #170
Signed-off-by: fupan.lfp <fupan.lfp@antfin.com>
=> elections: 2020-09

elections/arch-committee-2020-09/FabianoFidencio.txt
Declare myself a candidate for one seat on the Kata Containers
Architecture Committee.
Fixes: #175
=> elections: Add Fabiano Fidêncio candidacy

elections/arch-committee-2020-09/README.md
Let's have each one of the dates as a list item, so it can be properly
rendered.
Fixes: #173
=> elections | 2020-09: Fix date formatting

elections/arch-committee-2020-09/EricErnst.txt
I'm having fun -- let's keep going!
Fixes: #179
Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>
=> election: Add Eric Ernst's candidacy for Kata AC

elections/arch-committee-2020-09/JustinHe.txt
Let's make Kata better, especially on arm64 :)
Fixes: #181
Signed-off-by: Jia He <justin.he@arm.com>
=> election: Add Justin He's candidacy for Kata AC

elections/arch-committee-2020-09/ArchanaShinde.txt
Want to add my candidacy for 09-2020 elections.
Fixes: #183
=> election: Add candidacy for Kata AC

VMT/KCSA.md, VMT/KCSA/KCSA-CVE-2020-28914.md
VMT: add KCSA for CVE-2020-28914
We have fixed them and put the fix in a release. Let's
make the announcement.
Fixes: #187
=> Add KCSA for CVE-2020-28914

VMT/KCSA.md
Various improvements to the KCSA document including:
- Add "Date" (of announcement) and "Affected Versions" columns to table.
- Sort table rows by date.
- Add section showing how to determine which version of Kata you are using.
- Add section with references to upgrading doc if you are affected by a KCSA.
- Add table of contents.
Fixes: #189.
=> docs: Improve formatting and content of KCSA document

elections/README.md, elections/arch-committee-2021-02/README.md, elections/arch-committee-2021-02/Results.md
Add the details and documentation for the February 2021 elections.
Fixes: #198
=> elections: 2021-02

elections/arch-committee-2021-02/PengTao.txt
Ant Group nominates @bergwolf as a candidate for AC
Fixes: #202
=> elections: Add Peng Tao candidacy

elections/arch-committee-2021-02/SamuelOrtiz.txt
I'd like to run for a renewal of my AC seat.
Fixes: #204
=> elections: 2021-02: Add Samuel Ortiz candidacy

elections/arch-committee-2020-09/Results.md
Four nominations were received for the September 2020 elections:
- [`Archana Shinde`](https://github.com/amshinde) 
- [`Eric Ernst`](https://github.com/egernst)
- [`Fabiano Fidêncio`](https://github.com/fidencio)
- [`Justin He`](https://github.com/justin-he)
Three seats were available, so elections were held.
The nominees elected to the positions were:
- [`Archana Shinde`](https://github.com/amshinde)                                                                                  
- [`Eric Ernst`](https://github.com/egernst)
- [`Fabiano Fidêncio`](https://github.com/fidencio)
Congratulations to our new architecture committee members Fabiano and Archana and our continuing member Eric!
=> add the 2020-09 elections results

README.md
I now work for Apple.
Fixes #221
Signed-off-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>
=> README: Change my employer

elections/README.md, elections/arch-committee-2021-09/README.md, elections/arch-committee-2021-09/Results.md
Adding the README.md file
Fixes: #227
Signed-off-by: Ricardo Aravena <raravena80@gmail.com>
=> elections: Arch Committee September 2021

elections/arch-committee-2021-09/EricErnst.txt
Add myself as a candidate for the 09/2021 AC election.
Fixes: #231
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
=> elections: add my candidacy

elections/arch-committee-2021-09/ArchanaShinde.txt
Adding my candidacy for Kata AC September 2021 elections.
=> elections: Announcing my candidacy

elections/README.md, elections/arch-committee-2022-03/README.md, elections/arch-committee-2022-03/Results.md
Add the details and documentation for the March 2022 elections.
Fixes: #255
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>
=> elections: 2022-03

elections/arch-committee-2022-03/TaoPeng.txt
Adding my candidacy for Kata AC March 2022 elections.
Fixes: #258
=> elections: Announcing Tao Peng's candidacy

elections/arch-committee-2022-03/SamuelOrtiz.txt
I'd like to run for a renewal of my AC seat.
Fixes #261
Signed-off-by: Samuel Ortiz <s.ortiz@apple.com>
=> elections: 2022-03: Add Samuel Ortiz candidacy

CONTRIBUTING.md
Update master to main in instructions and relevant links.
Fixes #283
Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>
=> contributing: Update outdated repo branch name

Backport-Guide.md
Updates auto-backport documentation and changes instances of master with
main.
Fixes #286
Signed-off-by: Derek Lee <derlee@redhat.com>
=> backporting-docs: Add auto-backport

elections/README.md, elections/arch-committee-2022-11/README.md, elections/arch-committee-2022-11/Results.md
Add the details and documentation for the November 2022 elections.
Fixes: #291
Signed-off-by: bin liu <bin@hyper.sh>
=> elections: 2022-11

elections/arch-committee-2022-11/FengWang.txt
Add my candidacy for the Kata Containers Architecture Committee election.
Fixes: #295
Signed-off-by: Feng Wang <feng.wang@databricks.com>
=> elections: Add Feng Wang candidacy

elections/arch-committee-2022-11/FupanLi.txt
Add my candidacy for the Kata Containers Architecture Committee.
Fixes: #297
Signed-off-by: Fupan Li <fupan.lfp@antgroup.com>
=> Add Fupan.li's election doc

elections/arch-committee-2022-11/EricErnst.txt
Add candidacy doc.
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
=> elections: Add Eric Ernst candidacy

elections/arch-committee-2022-11/ArchanaShinde.txt
Add my candidacy for the Kata Containers Architecture Committee elections for 11/2022.
Fixes: #300
=> elections: Add candidacy doc for Archana Shinde.

elections/arch-committee-2022-11/GerryLiu.txt
Add my candidacy for the Kata Containers Architecture Committee election.
Fixes: #302
Signed-off-by: Jiang Liu <gerry@linux.alibaba.com>
=> Add my candidacy for the Kata Containers Architecture Committee election

elections/tools/generate_electorate.py
Some github API short commits are missing the author name. Do not skip those commits if the core git commit below it does contain the author information.
Fixes: #306
Signed-off-by: Samuel Ortiz <sameo@rivosinc.com>
=> tools: Only skip commits when the core git commit is incomplete

.github/workflows/main.yml, README.md, elections/arch-committee-2022-11/Results.md
And update some Architecture Committee members' info.
Signed-off-by: bin liu <bin@hyper.sh>
=> elections: add the 2022-11 elections results

elections/README.md, elections/arch-committee-2023-04/README.md, elections/arch-committee-2023-04/Results.md
Add details and documentation for the April 2023 elections.
Fixes: #327
=> elections: 2023-04

elections/arch-committee-2023-04/TaoPeng.txt
Add my candidacy as I certainly want to continue my contribution to the kata community.
=> election: add Tao Peng's candidacy

elections/arch-committee-2023-04/SamuelOrtiz.txt
I'd like to continue helping the Kata Containers and Confidential Containers projects by renewing my AC seat.
Fixes #336
=> elections: Add Samuel Ortiz candidacy for the 2023-04 elections

elections/arch-committee-2023-04/JeremiPiotrowski.txt
I would like to run for a seat on the Architecture Committee in the April 2023 election.
Fixes: #338
=> elections: Add Jeremi Piotrowski candidacy

elections/arch-committee-2023-04/SteveHorsman.txt
Add candidacy in the April 2023 Architecture Committee election
Fixes: #340
=> elections: Add Steve Horsman candidacy

elections/README.md, elections/arch-committee-2023-10/README.md, elections/arch-committee-2023-10/Results.md
Add details and documentation for the October 2023 elections.
Fixes: #349
=> election: 2023-10

elections/arch-committee-2023-10/FabianoFidencio.txt
I would like to rerun for a seat on the Architecture Committee in the October 2023 election.
Fixes: #351
=> election: 2023-10: Add Fabiano Fidêncio candidacy

elections/arch-committee-2023-10/ZvonkoKaiser.txt
Add my candidacy for the October 2023 cycle.
Fixes: #353
=> election: 2023-10 Add Zvonko Kaiser candidacy

elections/arch-committee-2023-10/JeremiPiotrowski.txt
Throwing my hat in the ring.
Fixes: #357
=> election: 2023-10: Add Jeremi Piotrowski candidacy

elections/arch-committee-2023-10/FupanLi.txt
Add my candidacy for the October 2023 cycle.
Fixes: #359
=> election: 2023-10 Add Fupan Li candidacy

elections/arch-committee-2023-10/GregKurz.txt
First tentative to join the AC.
Fixes: #361
=> election: 2023-10: Add Greg Kurz's candidacy

elections/arch-committee-2023-10/GerryLiu.txt
Run for 2023 AC election.
Fixes: #364
=> election: 2023-10: Add Gerry Liu's candidacy

README.md
=> docs: update seats count from 5 to 7

elections/tools/generate_electorate.py
- Update ignored repos to include dbs-snapshot and cgroups-rs which are forked/imported
Fixes: #369
=> tools: Update generate_electorate.py

elections/arch-committee-2023-10/README.md
- Update dates of election to reflect delay in the voting period
Fixes: #373
=> election: 2023-10 fix dates

README.md, elections/arch-committee-2023-10/Results.md
Formally record the results of the Fall 2023 election in Github
=> 2023 10 election results

elections/README.md
This patch fixes the current size of the AC, which grew to 7 members from the previous 5.
=> Updating the number of AC seats

README.md, elections/arch-committee-2024-04/README.md
After 3.5 years serving the community as part of the Architecture Committee, this is the time for me to step down, and save some time to focus on specific areas of the project that I currently am lacking the time to do so.
It's been an amazing ride, I'm thankful for all we could achieve together, and I won't be a strange in the community.
=> readme/elections: Fabiano Fidêncio is stepping down

elections/arch-committee-2024-04/AnastassiosNanos.txt
Submit candidacy for 2024 Spring AC elections.
Fixes: #394
=> elections: Add ananos' candidacy for the AC

elections/arch-committee-2024-10/GregKurz.txt
=> election: 2024-10: Add Greg Kurz's candidacy

elections/arch-committee-2024-10/FupanLi.txt
Submit candidacy for 2024 Oct AC elections.
=> election: 2024-10: Add Fupan Li's candidacy

elections/arch-committee-2024-10/WainerMoschetta.txt
My candidacy for 2024 Oct AC elections
=> election: 2024-10: Add Wainer Moschetta's candidacy

elections/arch-committee-2024-10/AurelienBombo.txt
My candidacy for the elections!
=> election: 2024-10: Add Aurelien Bombo's candidacy

elections/arch-committee-2025-04/RuoqingHe.txt
Add candidacy for the April 2025 Architecture Committee election.
=> elections: Add Ruoqing He candidacy

elections/arch-committee-2025-04/ZvonkoKaiser.txt
Add Zvonko Kaiser candidacy for the H1 2025 cycle
=> Add Zvonko Kaiser candidacy for the H1 2025 cycle

elections/arch-committee-2025-04/AnastassiosNanos.txt
Add the text for Anastassios Nanos' candidacy in the upcoming kata AC elections (Apr 25).
=> elections: Add Anastassios Nanos candidacy

elections/arch-committee-2025-04/TaoPeng.txt
To the 2025 spring AC member election.
=> elections: Add Tao Peng's candidacy

elections/arch-committee-2025-10/AurelienBombo.txt
My candidacy for the election!
=> elections: Add Aurelien Bombo's candidacy

elections/arch-committee-2025-10/GregKurz.txt
=> election: 2025-10: Add Greg Kurz's candidacy

elections/arch-committee-2025-10/FupanLi.txt
Renew Fupan Li's candidacy info.
=> election: 2025-10: add Fupan Li's candidacy
