kata-containers/community

README.md

Fix up a few typos and format slips.
Add the link for the 'four opens'.
Reword who can vote on committee members from 'anyone who has merged code'
(which would only be maintainers?) to 'anyone who has had code merged'
(which would be all contributors), which I believe is the intent.

README: Minor fixups

---

.pullapprove.yml

Add a Pullapprove config file to require 2 ack's for all PRs.
Fixes #12.

CI: Add pullapprove config

---

README.md

For clarity, list all members of the Architecture Committee as a list,
with appropriate links.
Also created a separate subsection to allow for a quick jump to current
members.
Fixes #18.

docs: Specify Architecture Committee & Working Committee members as list

---

VENDORING.md

The new `dep` now automatically prunes, and has deprecated the
command line prune command.
Update the doc to reflect this. Also add a note that we like to
use the `non-go = true` option for prune as well if we can.
Fixes: #20
Signed-off-by: Graham whaley <graham.whaley@intel.com>

vendoring: update information around `prune`

---

CONTRIBUTING.md

Updated the contributing doc to explain that only a single commit in the
PR commit range needs to have a "`Fixes #XXX`" comment.
Fixes #28.

docs: Rework patch format section in contributing guide

---

CONTRIBUTING.md

The Kata project doesn't use `OWNERS` files so rework the "Project
Maintainers" section of the contribution guide to explain who the
Approvers are and how the approval process works.
Fixes #30.

docs: Remove mention of OWNERS files from contrib guide

---

CONTRIBUTING.md

Add a section to the contributing guide explaining how we handle PRs
that are valuable but where the creator is either unable to progress
them, or is absent.
Fixes #43.

docs: Document assisted PR review process

---

CONTRIBUTING.md

The CONTRIBUTING doc contained an extraneous command in the
"Re-vendor PRs" section which makes the command invalid.
Fixes #49.

docs: Remove stray bracket from contributing doc command

---

CONTRIBUTING.md
README.md

Move the contact details to the top-level README in a new "Join Us" section.
This PR is based on (and replaces) https://github.com/kata-containers/community/pull/23.
Fixes #51.
Contributions-from: Josh Berkus <jberkus@redhat.com>
Contributions-from: Kristi Rifenbark <kristix.rifenbark@intel.com>

docs: Make contact details more prominent

---

elections/arch-committee-2018-09/2018-09-Results.txt

Adds the election results for the September
2018 Architecture Committee election.
Signed-off-by: Anne Bertucio <anne@openstack.org>

Adds 2018-09 Election Results

---

README.md

Updates the README to reflect September 2018
election and adjusts verbage to reflect that we have
had our first election (vs "There will be an election
in September 2018).
Signed-off-by: Anne Bertucio <anne@openstack.org>

Updates README with election results

---

Backport-Guide.md
CONTRIBUTING.md

Add some docs to note we require bug/feature labels on PRs
so we can work out what needs to be a stable backport or not.
Also add a brief doc on how to cherry pick and base/push to
a stable branch PR.
Fixes: #63

docs: contrib: document stable branch backports

---

CONTRIBUTING.md

Add a full example of creating a PR including explaining how to rebase,
squash commits and force push to include review changes.
Fixes #66.

docs: Add full PR example to contributing guide

---

CONTRIBUTING.md

If following the contributing doc and wanting to run make check and
make test in kata-runtime, the virtcontainers/bin/hook executable
is expected to exist. But it only exists if it is compiled and
installed. So a note has been added that if make test|check for
runtime, to ensure that virtcontainers has been compiled and
installed.

docs: add note about virtcontainers if testing runtime

---

README.md
VMT/KCSA.md
VMT/KCSA/KCSA-CVE-2019-5736.md

Add the KCSA for CVE-2019-5736.
As this is our first KCSA, also create the KCSA index page and
reference that from the top level README.
Fixes: #85

VMT: CVE-2019-5736: runc escape

---

CONTRIBUTING.md

With the move away from pullapprove and towards github and
Zuul for ack accounting, SoB and WIP checks, we need to update
the documents to reflect this.
Fixes: #76

CONTRIB: Update to reflect new CI workflows

---

CONTRIBUTING.md

If working on the runtime, it is necessary to return to the top-level directory after having built `virtcontainers`.
Make this clearer by using a `pushd` and `popd` pair rather than a single `cd`.
Fixes #93.

docs: Clarify virtcontainers build

---

README.md
elections/README.md

Add missing links to documents to ensure all docs in this repo can be discovered easily.
Fixes #99.

docs: Add missing doc links

---

README.md
Rota-Process.md

Add a new document explaining what the Kata Rota Team is and what they should do.
Fixes: #104.

docs: Add new Rota doc

---

README.md

Now we have the table of Kata resources and owners on a wiki page,
let's link it from the main community README to make it easier
to find.
Fixes: #71

README: Add link to resource owners wiki page

---

README.md

They were still aliased to the previous members.
Fixes: #128

README: Fix the architecture committee members github links

---

README.md

The Slack invitation URL expired (boo!) so update to the new one.
Fixes: #130.

docs: Update Slack invitation URL

---

README.md

How to report vulnerabilities was not clearly documented. Add a section
noting you can use either the launchpad or email.
Fixes: #132

docs: vulnerabilities: document how to report vulnerabilities

---

VMT/KCSA.md
VMT/KCSA/KCSA-CVE-2020-2024.md
VMT/KCSA/KCSA-CVE-2020-2025.md

We have fixed them and put the fix in a release. Let's
make the announcement.
/cc @YuvalAvra

VMT: add KCSAs for CVE-2020-2024 and CVE-2020-2025

---

VMT/KCSA.md
VMT/KCSA/KCSA-CVE-2020-2023.md
VMT/KCSA/KCSA-CVE-2020-2026.md

These have been fixed and put in releases 1.11.1 and 1.10.5.
Sending out announcement.

VMT: add KCSA for CVE-2020-2023 and CVE-2020-2026

---

README.md

Moved again, let's make it official.
Fixes: #160
Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>

architecture-committee: Update Eric's employer

---

CONTRIBUTING.md

Fixes #163 
The Signed-off-by line should also contain the name of the contributor.
Fix it in the documentation.
Signed-off-by: Jens Freimann <jfreiman@redhat.com>

docs: correct contributor guide Signed-off-by example

---

README.md

As a result of the elections that took place in Sep - Oct 2020,
Archana Shinde and Fabiano Fidêncio became part of the Architecture
Committee.
Fixes: #185

README: Update Architecture Committee members

---

VMT/KCSA.md
VMT/KCSA/KCSA-CVE-2020-27151.md

An insufficient validation of annotations affects Kata Containers prior to
version 1.11.5, making it possible to execute arbitrary programs on the
host. Unless specific filtering of the annotations is performed by the upper
layers of the stack, it makes it possible for a user to send manifests that
instruct kata-runtime to execute arbitrary code with the same privilege level as
kata-runtime itself.
Fixes: #191
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>

security: Create KCSA for CVS-2020-27151

---

elections/arch-committee-2021-02/README.md

Due to issues with the Kata Containers ML, the Architecture Committee
has agreed on postponing the election by one week.
This PR updates the dates according to the decision taken as part of the
Architecture Committee meeting held on March 2nd, 2021.
Fixes: #200

elections: Adjust the dates for the 2021-02 round 2

---

AC-Meeting-Guidelines.md
README.md

The goal here is to avoid spending time on discussions that could be
much more efficiently and inclusively discussed through github issues or
on the mailing list.
Fixes: #196

README: Define guidelines for adding topics to the AC meetings agenda

---

README.md
elections/arch-committee-2021-02/Results.md

Two nominations were received for the February 2021 elections:
- [`Peng Tao`](https://github.com/bergwolf)
- [`Samuel Ortiz`](https://github.com/sameo)
Two seats were available, so elections were over sooner.
The two members were (re-)admitted to the Architecture Committee on 2021-03-10
Fixes: #207

election: Publish results for 2021-02 round

---

CONTRIBUTING.md

If you edit a doc in Windows there is a good chance the
editor will add CRLF to the end instead of LF which
causes CI failures.
Fixes: 210
Signed-off-by: Eric Adams <eric.adams@intel.com>

docs: Add note for Windows users to use LF and not CRLF

---

CONTRIBUTING.md

`kata-agent` is written in Rust currently, so it is better to add a description about Rustlang coding style in the `CONTRIBUTING` document.
Fixes: #213
Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

docs: Add explanation about Rustlang coding style

---

README.md

Freenode is no longer the home of the kata-containers IRC channels.
Following the announcement on our mailing list, we've moved to OFTC:
http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001938.html
Fixes: #216

README: Point the IRC channels to OFTC

---

CONTRIBUTING.md

This PR removes the travis reference in the Continuous Integration
System as it is not longer supported.
Fixes #219
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

docs: Remove travis reference in the CI

---

README.md

Sunny Cai has created a link for us that won't expire anymore, let's use
it.
Fixes: #223

README: Update slack invitation link

---

README.md

Fabiano now works for Intel.
Fixes: #240
Signed-off-by: Fabiano Fidêncio <fabiano@fidencio.org>

README: Change Fabiano Fidêncio's employer

---

README.md

The current agenda link is https://etherpad.opendev.org/p/Kata_Containers_2022_Architecture_Committee_Mtgs 
Fixes: #251
Signed-off-by: Zack <zmlcc@linux.alibaba.com>

Update outdated agenda link in README.md

---

elections/arch-committee-2022-03/Results.md

Two nominations were received for the March 2022 elections:
- [`Peng Tao`](https://github.com/bergwolf)
- [`Samuel Ortiz`](https://github.com/sameo)
Two seats were available, so elections were over sooner.
The two members were (re-)admitted to the Architecture Committee on 2022-03-16
Fixes: #255
Signed-off-by: bin liu <liubin0329@gmail.com>

election: Publish results for 2022-03 round

---

CODE_OF_CONDUCT.md
README.md
VMT/VMT.md

Change some names/links from OpenStack Foundation
to Open Infrastructure Foundation.
Signed-off-by: bin liu <bin@hyper.sh>

docs: change openstack foundation to new name

---

CONTRIBUTING.md

Checkcommits has been removed from both tests and kata-containers and
replaced with a Github Action. This updates the documentation to reflect
that.
Checkcommits also contained style information that was not documented
elsewhere. These are now included in the docs as well.
Fixes #278
Signed-off-by: Derek Lee <derlee@redhat.com>

contributing: remove checkommit mentions+update body docs

---

elections/arch-committee-2022-11/FabianoFidencio.txt

Add my candidacy for renewing my seat on the Kata Containers Architecture Committee.
Fixes: #293
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

elections: Add Fabiano Fidêncio candidacy

---

elections/tools/generate_electorate.py

There are a bunch of repos that must be ignored for the elections purpose.  Those are archived repos for more than one year, and repos we forked for one reason or another.
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

elections/tools: Update ignored repos

---

elections/tools/generate_electorate.py

We've been ingoring branches of projects, and with that simply ignoring contributors to stable releases, and to efforts like Confidential Containers, runtime-rs, Peer Pods, etc.
Fixes: #310
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

elections: Go through project branches

---

README.md
elections/arch-committee-2023-04/Results.md
elections/tools/generate_electorate.py

My fellow Kata citizens,
The voting period ended on May 1st, and I'm excited to announce the
results of the Kata Containers Architecture Committee elections.
We had 6 candidates and 4 seats to fill up. The voters elected the
following members:
- Tao Peng
- Feng Wang
- Samuel Ortiz
- Steve Horsman
Congratulations to our new Architecture Committee members Feng and
Steve, and to Tao and Samuel for renewing their seats!
For more details about the ballot, please use the following link:
https://civs1.civs.us/cgi-bin/results.pl?id=E_55f8c62ec8ce23da
Please note that we are using the CIVS default completion rule
(Minimax) to build the election results.

elections: 2023-04 results

---

README.md
elections/tools/generate_electorate.py

I came across this issue today when I tried to sign-up to kata slack, so I took the liberty to refresh the PR.
Updated bit.ly link pointing to expired Slack invite to a working link.
Fixes: #315
Originally-by: OGtrilliams <tribecca@tribecc.us>
Closes: #316

readme: Update Slack invite link

---

README.md

The link is outdated, and also breaks static check action.

docs: update website link for antgroup

---

elections/README.md
elections/arch-committee-2024-04/README.md
elections/arch-committee-2024-04/Results.md

This patch creates the folder for the 2024 H1 AC elections. It also proposes an election timeline that intentionally avoids the dates of KubeCon EU and Easter.

Adding 2024 H1 AC election details

---

elections/README.md

This patch specifies the first day of the nomination period as the last day for anyone to qualify as eligible electorate.
This will help with building the electorate list earlier in the process, so election officials can make sure that everyone is included before creating the poll for the voting period.

Specifying timeline for defining the electorate

---

elections/arch-committee-2024-04/README.md

This patch adds Aurelien Bomboo and Alex Lyn as election officials for the upcoming Kata AC elections.

Adding election officials for 2024 H1 Kata AC elections

---

README.md
elections/arch-committee-2024-04/Results.md

Removes Fabiano and Samuel, and adds Anastassios and Zvonko.

readme: update AC following 2024 H1 elections

---

elections/README.md
elections/arch-committee-2024-10/README.md

This patch adds the timeline and creates the folder structure for the 2024 H4 AC election.

Adding 2024 H2 AC election timeline

---

elections/README.md
elections/process/README.md

This change adds a new folder to capture the election process and later on store email and other templates as needed.
The patch also adds some further information about CIVS and how to set up voting.

Add election process description

---

elections/arch-committee-2024-10/README.md

This patch adds  Alex Lyn and Steve Horsman as election officials for the upcoming Kata AC elections.

Adding election officials to Kata AC 2024 H2 election

---

elections/arch-committee-2024-10/README.md

Due to Golden week public holidays in China syncing with the candidate nomination period, we are extending this by a week and pushing the other dates back by the same in order to give everyone the chance to declare their candidacy

election: 2024-10: Update dates

---

README.md
elections/README.md
elections/arch-committee-2024-10/Results.md

This patch updates the AC after the election in October 2024. The patch removes Gerry Liu and adds Aurelien Bombo to the currnet AC.

readme: update AC following 2024 H2 elections

---

README.md

Update the contributor role descriptions and guidelines for review, based on the vPTG discussion

doc: Governance Roles

---

elections/README.md
elections/arch-committee-2025-04/README.md
elections/arch-committee-2025-04/Results.md

This patch creates the folder for the 2025 H1 AC elections. It also proposes an election timeline that intentionally avoids the dates of KubeCon EU.

Adding 2025 H1 AC election details
